[deps]
ACDCStateEstimation = "12a95e38-0f0d-4102-861d-7ea40a75b0de"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsMCDC = "05d58fe5-e6ff-58ad-86d6-05dcc0b74504"
